name: linux
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Print Public IP
        run: |
          echo 'ipv4: ${{ steps.ip.outputs.ipv4 }}'
          echo 'ipv6: ${{ steps.ip.outputs.ipv6 }}'
      - run: ./install-frp.sh
      - name: run frpc
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPS_PORT: ${{ secrets.FRPS_PORT }}
          FRPS_TOKEN: ${{ secrets.FRPS_TOKEN }}
          FRPC_RPORT: ${{ secrets.FRPC_RPORT }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          J8: ${{ secrets.J8 }}
        run: ./j8frpc.sh
