name: Ubuntu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Print Public IP
        run: |
          echo 'ipv4: ${{ steps.ip.outputs.ipv4 }}'
          echo 'ipv6: ${{ steps.ip.outputs.ipv6 }}'
      - run: ./install-frp.sh
      - name: run frpc
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: ./j8frpc.sh
